/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package newsfetcher;

/*import com.sun.xml.internal.fastinfoset.stax.factory.StAXInputFactory;
import com.sun.xml.internal.stream.XMLInputFactoryImpl;*/
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Duong Dieu Phap
 */
public class frmMain extends javax.swing.JFrame {

    /*
     * Variable
     */
    public List<Website> listWebsite;
    public List<Category> listCategory;
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        LoadDanhSachTrang();
    }
    
    DataProvider dp = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblThongTinPhanMem = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbTrangWeb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbChuyenMuc = new javax.swing.JComboBox();
        btnThemTrangWeb = new javax.swing.JButton();
        btnXoaTrangWeb = new javax.swing.JButton();
        btnChinhSuaTrang = new javax.swing.JButton();
        btnXemTinTuc = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTest = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("News Fetcher");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("News Fetcher");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Phần mềm lấy tin tức tự động");

        lblThongTinPhanMem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblThongTinPhanMem.setText("Thông tin");
        lblThongTinPhanMem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongTinPhanMemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongTinPhanMemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongTinPhanMemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                        .addComponent(lblThongTinPhanMem)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblThongTinPhanMem))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setText("Trang web:");

        cmbTrangWeb.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int idx  = cmbTrangWeb.getSelectedIndex();
                LoadChuyenMuc(idx);
            }
        });

        jLabel4.setText("Chuyên mục:");

        btnThemTrangWeb.setText("Thêm trang mới");
        btnThemTrangWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTrangWebActionPerformed(evt);
            }
        });

        btnXoaTrangWeb.setText("Xoá trang web");
        btnXoaTrangWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangWebActionPerformed(evt);
            }
        });

        btnChinhSuaTrang.setText("Chỉnh sửa trang");
        btnChinhSuaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaTrangActionPerformed(evt);
            }
        });

        btnXemTinTuc.setText("Xem tin tức");
        btnXemTinTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTinTucActionPerformed(evt);
            }
        });

        btnTest.setText("Test xpath");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(cmbChuyenMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTrangWeb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnXemTinTuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTest)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnThemTrangWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChinhSuaTrang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaTrangWeb)
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTrangWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTrangWeb)
                    .addComponent(btnChinhSuaTrang)
                    .addComponent(btnThemTrangWeb))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbChuyenMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemTinTuc)
                    .addComponent(btnTest))
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtTest.setColumns(20);
        txtTest.setRows(5);
        jScrollPane1.setViewportView(txtTest);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Event Method
     */
    private void btnChinhSuaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaTrangActionPerformed
        // TODO add your handling code here:
        int idx = cmbTrangWeb.getSelectedIndex();
        int webID = listWebsite.get(idx)._id;
        frmWebsite f = new frmWebsite(webID);
        f.setVisible(true);
        
        f.addWindowListener(new WindowAdapter() {
            @Override 
            public void windowClosed(WindowEvent e) {
                LoadDanhSachTrang();
            }
        });
        
        
    }//GEN-LAST:event_btnChinhSuaTrangActionPerformed

    private void lblThongTinPhanMemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinPhanMemMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new JFrame(), 
                "Thông tin nhóm thực hiện:\n\n"
                + "Nguyễn Ngọc Khánh - 1241350\n"
                + "Bùi Bá Lộc - 1241363\n"
                + "Dương Diệu Pháp - 1241378\n"
                + "Nguyễn Quốc Tuấn - 1241431");
    }//GEN-LAST:event_lblThongTinPhanMemMouseClicked

    private void lblThongTinPhanMemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinPhanMemMouseEntered
        // TODO add your handling code here:
        lblThongTinPhanMem.setText("Thông tin <");
        lblThongTinPhanMem.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblThongTinPhanMemMouseEntered

    private void lblThongTinPhanMemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinPhanMemMouseExited
        // TODO add your handling code here:
        lblThongTinPhanMem.setText("Thông tin");
    }//GEN-LAST:event_lblThongTinPhanMemMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        // TODO add your handling code here:
        //dp = new DataProvider("./app.config");
        dp = new DataProvider("localhost", "dbNewsFetcher", 1433, true, "sa", "");
        //JOptionPane.showMessageDialog(this, "Kết nối CSDL: " + dp.isConnected());
    }//GEN-LAST:event_formWindowOpened

    private void btnXemTinTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTinTucActionPerformed
        
    }//GEN-LAST:event_btnXemTinTucActionPerformed

    private void btnThemTrangWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTrangWebActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser(".\\xml");
        c.setFileFilter(new FileNameExtensionFilter("XML Files (*.xml)", "xml"));
        
        if(c.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            int websiteID = ReadWriteXML.ReadXML(c.getSelectedFile());
            frmWebsite f = new frmWebsite(websiteID);
            f.setVisible(true);
            
            LoadDanhSachTrang();
        }
    }//GEN-LAST:event_btnThemTrangWebActionPerformed

    private void btnXoaTrangWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangWebActionPerformed
        
        try {
            int idx = cmbTrangWeb.getSelectedIndex();
            int webID = listWebsite.get(idx)._id;
            
            Website.deleteWebsite(webID);
            LoadDanhSachTrang();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaTrangWebActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        
        try {
            
            List<Category> categories = new ArrayList<>();
            Category cat = new Category();
            
            /*
            cat._name = "Quốc tế";
            cat._url = "http://nld.com.vn/thoi-su-quoc-te.htm";
            cat._xpathLayout = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div";
            
            cat._link = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[1]/h3/a/@href";
            cat._title = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[1]/h3/a";
            cat._image = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[1]/a/img/@src";
            cat._date = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[1]/p[1]";
            cat._description = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[1]/p[2]";
            cat._nextpage = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[11]/a[2]";
            cat._xpathNextPage = "//*[@id=\"content\"]/div[1]/div[3]/div[2]/div[11]";
            
            
            cat._name = "Du học";
            cat._url = "http://ione.vnexpress.net/tin-tuc/hoc-duong/du-hoc";
            cat._xpathLayout = "//*[@id=\"ione_tinnoibat_khac\"]/div";
            cat._link = "//*[@id=\"ione_tinnoibat_khac\"]/div/div[2]/h3/a/@href";
            cat._title = "//*[@id=\"ione_tinnoibat_khac\"]/div/div[2]/h3/a";
            cat._image = "//*[@id=\"ione_tinnoibat_khac\"]/div/div[2]/div/a/img/@src";
            cat._date = "//*[@id=\"ione_tinnoibat_khac\"]/div/div[1]/div[1]";
            cat._description = "//*[@id=\"ione_tinnoibat_khac\"]/div/div[2]/p";
            cat._nextpage = "//*[@id=\"contain\"]/div[3]/div[1]/div[2]/ul/li[2]/a";
            cat._xpathNextPage = "//*[@id=\"contain\"]/div[3]/div[1]/div[2]/ul";
            
            /*
            cat._name = "Fashion";
            cat._url = "http://kenh14.vn/fashion/trang-2.chn";
            cat._xpathLayout = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[1]/ul/li";
            cat._link = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[2]/ul/li[1]/h2/a/@href";
            cat._title = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[1]/ul/li[1]/h2/a";
            cat._image = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[1]/ul/li[1]/a/img/@src";
            cat._date = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[1]/ul/li[1]/p[1]/span/@title";
            cat._description = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[1]/ul/li[1]/p[2]/text()";
            cat._nextpage = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[2]/a[3]";
            cat._xpathNextPage = "//*[@id=\"form1\"]/div[5]/div/div/div[3]/div[2]";
            */
            
            cat._name = "Chính trị xã hội";
            cat._url = "http://www.thanhnien.com.vn/pages/chinh-tri-xa-hoi.aspx";
            cat._xpathLayout = "//*[@id=\"divtoptin\"]";
            cat._link = "//*[@id=\"divtoptin\"]/div[1]/a/@href";
            cat._title = "//*[@id=\"divtoptin\"]/div[1]/a";
            cat._image = "//*[@id=\"divtoptin\"]/div[2]/div[1]/a/img/@src";
            cat._date = "//*[@id=\"divtoptin\"]/div[1]/span";
            cat._description = "//*[@id=\"divtoptin\"]/div[2]/div[2]/text()";
            cat._nextpage = "//*[@id=\"ctl00_m_g_6000cd1a_7fe3_4098_b899_5e9f4034e834\"]/div[2]/div[11]/div[2]/div[11]/div/a";
            cat._xpathNextPage = "//*[@id=\"ctl00_m_g_6000cd1a_7fe3_4098_b899_5e9f4034e834\"]/div[2]/div[11]/div[2]/div[11]/div";
            
            
            categories.add(cat);
            
            Website web = new Website();
            web._name = "Người lao động";
            web._url = "http://www.thanhnien.com.vn";
            web._categories = categories;
            
            
            HTMLReader html = new HTMLReader(new URL(cat._url));
            
            List<Content> ds = html.fetchNews(web._url, cat, 4);
            
            
            
            txtTest.setText(" ");
            
            for (int i = 0; i < ds.size(); i++) 
            {
                String re = "";
                
                re += "Title = " + ds.get(i)._title + "\n";
                re += "Link = " + ds.get(i)._link + "\n";                
                re += "Date = " + ds.get(i)._date + "\n";
                re += "Image = " + ds.get(i)._image + "\n";
                re += "Description = " + ds.get(i)._description + "\n\n\n";
                
                txtTest.setText(txtTest.getText() + re);
            }
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTestActionPerformed

    
    /*
     * Main method
     */
    private void LoadDanhSachTrang() {
        try {
            cmbTrangWeb.removeAllItems();
            listWebsite = Website.getListWebsite();
            
            for (int i = 0; i < listWebsite.size(); i++) {
                cmbTrangWeb.addItem(listWebsite.get(i)._name);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    }
    
    private void LoadChuyenMuc(int idx) {
        try {
            cmbChuyenMuc.removeAllItems();
            listCategory = listWebsite.get(idx)._categories;
            
            for (int i = 0; i < listCategory.size(); i++) {
                cmbChuyenMuc.addItem(listCategory.get(i)._name);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChinhSuaTrang;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnThemTrangWeb;
    private javax.swing.JButton btnXemTinTuc;
    private javax.swing.JButton btnXoaTrangWeb;
    private javax.swing.JComboBox cmbChuyenMuc;
    private javax.swing.JComboBox cmbTrangWeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThongTinPhanMem;
    private javax.swing.JTextArea txtTest;
    // End of variables declaration//GEN-END:variables


    













}
